# Generated by Django 4.1.1 on 2023-03-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appProductos", "0002_rename_imggrande_producto_imagen_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="imagen",
            new_name="imgGrande",
        ),
        migrations.AddField(
            model_name="producto",
            name="imgPeque",
            field=models.ImageField(null=True, upload_to="iconos"),
        ),
    ]
